# Generated by Django 3.1.7 on 2021-03-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='orderMode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
